version: '3.8'

services:
  # PostgreSQL - Main database for storing everything
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: fractal_postgres
    environment:
      POSTGRES_DB: fractal_rmo
      POSTGRES_USER: fractal
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # Uses password from .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"  # Makes database accessible on port 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fractal"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis - Fast cache and message queue
  redis:
    image: redis:7-alpine
    container_name: fractal_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"  # Makes Redis accessible on port 6379

volumes:
  postgres_data:  # Stores database files
  redis_data:     # Stores Redis data
